[tool.poetry]
name = "zeroeventhub"
version = "0.1.0"
description = "Broker-less event streaming over HTTP"
authors = ["Vipps MobilePay"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/vippsas/zeroeventhub"
keywords = ["event-streaming"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
flake8 = "^6.0.0"
pylint = "^2.15.10"
black = "^22.12.0"
mypy = "^0.991"
pytest-mock = "^3.10.0"
poetry-types = "^0.3.5"
responses = "^0.22.0"
coverage = "^7.1.0"
mock-protocol = "^1.0.0"

[tool.poetry.group.types.dependencies]
types-requests = "^2.28.11.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[[tool.mypy.overrides]]
module = "mock_protocol.*"
ignore_missing_imports = true

[tool.pylint.parameter_documentation]
accept-no-param-doc = true
accept-no-raise-doc = false
accept-no-return-doc = true
accept-no-yields-doc = true
default-docstring-type = "default"
