name: Publish Python client to PyPI

on:
  push:
    tags:
      - python/v*

defaults:
  run:
    working-directory: ./python/zeroeventhub

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'
      - name: Install and configure Poetry
        run: |
          pip install poetry==1.8.4
          poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: poetry install --sync --only=main
      - name: Build package
        run: poetry build -vvv
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8
        with:
          packages-dir: python/zeroeventhub/dist/
