name: Run unit-tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build .
        working-directory: ./go
      - name: Test
        run: go test
        working-directory: ./go